# Generated by Django 3.0.3 on 2020-10-30 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('booklink', models.CharField(blank=True, max_length=200)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('price', models.CharField(blank=True, max_length=200)),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('date', models.CharField(blank=True, max_length=200)),
                ('imagelink', models.CharField(blank=True, max_length=200)),
                ('memo', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'unique_together': {('owner', 'isbn')},
            },
        ),
    ]
