# Generated by Django 3.0.3 on 2020-02-14 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_auto_20200212_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='candidates',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='elections.Candidate'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='polls',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='elections.Poll'),
        ),
    ]
